worker_processes auto;

events {
    worker_connections 1024;
}

http {
    include mime.types;
    default_type application/octet-stream;

    # Backend upstream (preparado para escalar a múltiples contenedores)
    upstream backend_app {
        server app-blue:8080;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
        # Redirigir el trafico base a la vista de salud usando Nginx
        # location = / { return 302 /api/health; } Comentado para habilitar Frontend
        
        # Omitir logs para rutas de health check comunes si se desea
        location = /api/health {
            proxy_pass http://backend_app;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            access_log off;
        }
    }
}
